WITH vals AS (
  SELECT
    CAST(SUM(CASE WHEN antecedent=1 AND consequent=1 THEN count ELSE 0 END) AS DECIMAL(38,10)) AS TP,
    CAST(SUM(CASE WHEN antecedent=1 AND consequent=0 THEN count ELSE 0 END) AS DECIMAL(38,10)) AS FP,
    CAST(SUM(CASE WHEN antecedent=0 AND consequent=1 THEN count ELSE 0 END) AS DECIMAL(38,10)) AS FN,
    CAST(SUM(CASE WHEN antecedent=0 AND consequent=0 THEN count ELSE 0 END) AS DECIMAL(38,10)) AS TN
  FROM &RuleCoverage&
)
SELECT
  CAST(CASE WHEN TP+FP = 0 THEN 0 ELSE TP/(TP+FP) END AS DECIMAL(30,24)) AS prec,
  CAST(CASE WHEN TP+FN = 0 THEN 0 ELSE TP/(TP+FN) END AS DECIMAL(30,24)) AS recall,
  CAST(CASE WHEN TN+FP = 0 THEN 1 ELSE TN/(TN+FP) END AS DECIMAL(30,24)) AS specificity,
  CAST((TP+TN)/(TP+FP+FN+TN) AS DECIMAL(30,24)) AS accuracy,
  CAST((FP+FN)/(TP+FP+FN+TN) AS DECIMAL(30,24)) AS error_rate
FROM vals
WHERE TP+FP+FN+TN > 0
