/**
 * Class representing single song in the jukebox
 *
 * @author Liam Cui
 * @author Tyler Ronnenberg
 */

public class Song {
    /** name of song artist */
    String artist;
    /** name of song */
    String songName;
    /** number of times the song has been played */
    int timesPlayed;

    /**
     * Constructor initializes song name, artist name,
     *      and sets times played to 0
     * @param artist Name of the artist of the song
     * @param songName Name of the song
     */
    public Song (String artist, String songName) {
        this.artist = artist;
        this.songName = songName;
        this.timesPlayed = 0;
    }
    /** Getter for artist field */
    public String getArtist() {
        return this.artist;
    }
    /** Getter for songName field */
    public String getSongName() {
        return this.songName;
    }
    /** Getter for timesPlayed field */
    public int getTimesPlayed() {
        return this.timesPlayed;
    }
    /** Method to add one to timesPlayed field */
    public void incrementTimesPlayed() {
        this.timesPlayed++;
    }

    /**
     * Equals method override.
     * Checks if two songs have the same artist name and song name.
     * Ignores number of times song has been played.
     * @param other Song to be compared to
     * @return True if songs are the same, false otherwise
     */
    @Override
    public boolean equals (Object other) {
        if (!(other instanceof Song))
            return false;
        Song otherSong = (Song) (other);
        return this.artist.equals(otherSong.artist) &&
                this.songName.equals(otherSong.songName);
    }

    /**
     * Method to get the hashcode for a given song.
     * Hashcode is generated by using built-in String hash code functions and
     *      a standard formula for generating hash codes.
     * @return integer representing the song object
     */
    @Override
    public int hashCode() {
        int result = 1;
        int c1 = this.artist.hashCode();
        int c2 = this.songName.hashCode();
        //Uses prime number 31 to avoid duplicate hashcodes
        result = 31 * result + c1;
        result = 31  * result + c2;
        return result;
    }

    /** toString override. Displays song artist and song name */
    @Override
    public String toString() {
        return "Artist: " + this.getArtist() + ", Song: " + this.getSongName();
    }
}