"""
CSCI-603 Mondrian recursion lab
Author: RIT CS
Author: Liam Cui

The mondrian square lab. This program prompts for a depth of
recursion (between 1-8) and random subdivisions. It then draws a pattern
similar to the famous paintings of the artist Piet Mondrian. The drawing is
generated by recursively subdividing the canvas in either uniform sized or
randomly sized (depending on input) rectangles of random colors(blue, red,
yellow, and white). The surface area of each color is tracked and printed
alongside the total surface area of the drawing.
"""

import turtle as t
import random

# depth range for input
MIN_DEPTH = 1
MAX_DEPTH = 8

# the four colors of rectangles
COLORS = ['blue', 'red', 'white', 'yellow']

# screen dimensions and inlay offset for image
WIDTH = 800
HEIGHT = 800
INLAY = 20

def init(depth: int, rand: bool) -> None:
    """
    Set up the display. This is called by:
        main

    :param depth: user's desired depth
    :param rand: random subdivisions or not
    """

    t.tracer(0) #instant rendering
    t.Screen().setup(WIDTH, HEIGHT) # set screen dimensions
    # world coordinates
    t.setworldcoordinates(-INLAY, -INLAY, WIDTH + INLAY, HEIGHT + INLAY)
    t.setpos(0, 0) # image will render in llx 0, lly 0, urx 800, ury 800
    t.pensize(1) # black pen outline size is 1
    t.title(f'Mondrian, depth={depth}, random={rand}, width={WIDTH}, '
            f'height={HEIGHT}') # title includes key values
    t.hideturtle() # hides turtle

def get_depth():
    """
    Gets and returns the depth of the recursion as an input integer 1 - 8. If
        input is invalid, the user will be notified and prompted again. This is
        called by: main

    :return: The desired depth for recursion as an integer value from 1 to 8.
    """

    while True:
        try:
            depth = int(input('Enter desired depth: '))
            if 0 < depth < 9:
                break
            else:
                print('Invalid input. Please try again.')
        except ValueError:
            print('Invalid input. Please try again.')
    return depth

def get_random():
    """
    Prompts an input asking [Y/N] if the user would like random subdivisions.
        If input is invalid then an invalid input message is printed and the
        user is prompted to try again. pReturns the boolean representation of
        the input; True allows random subdivisions. This is called by: main

    :return: The boolean representation of allowing random subdivisions.
    """

    while True:
        rand = input('Would you like random subdivisions? [Y/N]: ').lower()
        if rand == 'y' or rand == 'yes':
            return True
        elif rand == 'n' or rand == 'no':
            return False
        else:
            print('Invalid input. Please try again.')

def draw_rectangle(llx, lly, urx, ury):
    """
    Draws and colors a rectangle. Rectangles size is determined by the
        parameters. rectangle colors options are Blue, Red, Yellow and White
        and are chosen at random. The function calculates and returns the
        surface areas of each color present in the rectangle. Only one color is
        used so the return will result in only one color with a positive
        surface area value and the rest have 0. This is called by:
        draw_rectangle_rec

    :pre: turtle facing east, square up, lower left corner, pen down
        or turtle facing west, square down, upper right corner, pen down
    :post: -"- respectively
    :param llx: lower left x coordinate
    :param lly: lower left y coordinate
    :param urx: upper right x coordinate
    :param ury: upper right y coordinate
    :return: Surface areas of each color in the drawn rectangle.
    """

    blue = 0
    red = 0
    yellow = 0
    white = 0
    color = random.choice(COLORS)
    t.fillcolor(color)
    t.begin_fill()
    for _ in range(2):
        t.forward(urx-llx)
        t.left(90)
        t.forward(ury-lly)
        t.left(90)
    t.end_fill()
    size = (urx - llx) * (ury - lly)
    if color == 'blue':
        blue = size
    if color == 'red':
        red = size
    if color == 'yellow':
        yellow = size
    if color == 'white':
        white = size
    return blue, red, yellow, white

def draw_rectangle_rec(llx, lly, urx, ury, depth, rand):
    """
    Calls the draw_rectangle function to draw the outer rectangle and then uses
        the depth parameter to determine how many times the function
        recursively calls itself to subdivide the rectangle. And uses the rand
        parameter to determine whether the subdivisions are randomly sized or
        uniform. The surface areas of each color used in the final drawing are
        recorded and returned. This is called by: main

    :pre: turtle facing east, square up, lower left corner, pen down
    :post: -"-
    :param llx: lower left x coordinate
    :param lly: lower left y coordinate
    :param urx: upper right x coordinate
    :param ury: upper right y coordinate
    :param depth: depth of the recursion
    :param rand: random subdivisions or not
    :return: Surface areas of each color in the drawn rectangle.
    """

    b, r, y, w = draw_rectangle(llx, lly, urx, ury)
    blue = int()
    red = int()
    yellow = int()
    white = int()
    if depth == 1: # get and return the most subdivided rectangle surface area
        blue = b
        red = r
        yellow = y
        white = w
        return blue, red, yellow, white
    else:
        if rand: # random multiplier between .1 and .9 increments of .01
            rand_x = random.randint(1, 9) * 0.1 #multiplier for x
            rand_y = random.randint(1, 9) * 0.1 #multiplier for y
        else: # halving multiplier for uniform subdivisions
            rand_x = rand_y = 0.5
        #subdivided lengths
        rand_llx = int(rand_x * llx)
        rand_urx = int(rand_x * urx)
        rand_lly = int(rand_y * lly)
        rand_ury = int(rand_y * ury)
        b1, r1, y1, w1 = draw_rectangle_rec(rand_llx, rand_lly,
                                            rand_urx, rand_ury,
                                            depth - 1, rand)
        t.forward(rand_x * urx)
        b2, r2, y2, w2 = draw_rectangle_rec(llx - rand_llx, rand_lly,
                                            urx - rand_urx, rand_ury,
                                            depth - 1, rand)
        t.forward((1 - rand_x) * urx)
        t.left(90)
        t.forward(ury)
        t.left(90)
        b3, r3, y3, w3 = draw_rectangle_rec(llx - rand_llx, lly - rand_lly,
                                             urx - rand_urx, ury - rand_ury,
                                             depth - 1, rand)
        t.forward((1 - rand_x) * urx)
        b4, r4, y4, w4 = draw_rectangle_rec(rand_llx, lly - rand_lly,
                                            rand_urx, ury - rand_ury,
                                            depth - 1, rand)
        t.forward(rand_x * urx)
        t.left(90)
        t.forward(ury)
        t.left(90)
        blue += b1 + b2 + b3 + b4
        red += r1 + r2 + r3 + r4
        yellow += y1 + y2 + y3 + y4
        white += w1 + w2 + w3 + w4
        return blue, red, yellow, white

def print_color_sizes(blue, red, yellow, white):
    """
    Takes the surface areas of each color as parameters and prints these
        surface areas and the sum of all these surface areas. This is called
        by: main

    :param blue: surface area of blue in the drawn image.
    :param red: surface area of red in the drawn image.
    :param yellow: surface area of yellow in the drawn image.
    :param white: surface area of white in the drawn image.
    :print: surface areas of each color in the drawn image and their sum.
    """

    print('Rectangle Surface Area:\n    blue: ', blue, '\n    red: ', red,
          '\n    yellow: ', yellow, '\n    white: ', white)
    print('Total surface area: ', blue + red + yellow + white)

def main() -> None:
    """
    The main method.
    """

    depth = get_depth()
    rand = get_random()
    init(depth, rand)
    blue, red, yellow, white = draw_rectangle_rec(0, 0, WIDTH, HEIGHT,
                                                  depth, rand)
    print_color_sizes(blue, red, yellow, white)
    t.mainloop()

if __name__ == '__main__':
    main()
